debug

diff --git a/.github/workflows/zap.yaml b/.github/workflows/zap.yaml
--- a/.github/workflows/zap.yaml
+++ b/.github/workflows/zap.yaml
@@ -87,41 +87,6 @@ jobs:
       - name: Install dependencies
         run: python3 -m pip install -r .security/requirements.txt
 
-      - name: Build Docker image for PR Branch
-        run: |
-          docker rmi my-web-app-pr:latest || echo "Docker image for PR branch not found"
-          docker build -t my-web-app-pr:latest .
-          echo "Docker image built for PR branch"
-
-      - name: Start web app for PR Branch
-        run: |
-          # docker run -d --name my-web-app-pr --network zapnet -p 127.0.0.1:${{ env.WEB_APP_HOST_PORT }}:${{ env.WEB_APP_CONTAINER_PORT }} bkimminich/juice-shop
-          docker run -d --name my-web-app-pr --network zapnet -p 127.0.0.1:${{ env.WEB_APP_HOST_PORT }}:${{ env.WEB_APP_CONTAINER_PORT }} my-web-app-pr:latest
-          echo "Waiting for PR branch web app..."
-          until curl -sSf http://localhost:${{ env.WEB_APP_HOST_PORT }}; do sleep 5; done
-          echo "PR branch web app is ready"
-
-      - name: Run ZAP Security Scan on PR Branch
-        run: |
-          echo "Running scan on PR branch..."
-          python3 .security/scan.py
-        env:
-          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
-          ZAP_PORT: ${{ env.ZAP_PORT }}
-          TARGET_URL: http://my-web-app-pr:${{ env.WEB_APP_CONTAINER_PORT }}
-          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-          ZAP_HOST: http://localhost
-          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
-          GITHUB_REPO: ${{ github.repository }}
-          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number || '' }}  # If PR exists
-          REPORT_SUFFIX: pr
-
-      - name: Delete web app for PR Branch
-        if: always()
-        run: |
-          docker rm -f my-web-app-pr || true
-          docker rmi my-web-app-pr:latest || true
-          echo "PR branch web app deleted"
 
       - name: Build Docker image for Main Branch
         run: |
@@ -161,6 +126,42 @@ jobs:
           docker rm -f my-web-app-main || echo "Docker image for Main branch not found"
           docker rmi my-web-app-main:latest || true
           echo "Main branch web app deleted"
+
+      - name: Build Docker image for PR Branch
+        run: |
+          docker rmi my-web-app-pr:latest || echo "Docker image for PR branch not found"
+          docker build -t my-web-app-pr:latest .
+          echo "Docker image built for PR branch"
+
+      - name: Start web app for PR Branch
+        run: |
+          # docker run -d --name my-web-app-pr --network zapnet -p 127.0.0.1:${{ env.WEB_APP_HOST_PORT }}:${{ env.WEB_APP_CONTAINER_PORT }} bkimminich/juice-shop
+          docker run -d --name my-web-app-pr --network zapnet -p 127.0.0.1:${{ env.WEB_APP_HOST_PORT }}:${{ env.WEB_APP_CONTAINER_PORT }} my-web-app-pr:latest
+          echo "Waiting for PR branch web app..."
+          until curl -sSf http://localhost:${{ env.WEB_APP_HOST_PORT }}; do sleep 5; done
+          echo "PR branch web app is ready"
+
+      - name: Run ZAP Security Scan on PR Branch
+        run: |
+          echo "Running scan on PR branch..."
+          python3 .security/scan.py
+        env:
+          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
+          ZAP_PORT: ${{ env.ZAP_PORT }}
+          TARGET_URL: http://my-web-app-pr:${{ env.WEB_APP_CONTAINER_PORT }}
+          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+          ZAP_HOST: http://localhost
+          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
+          GITHUB_REPO: ${{ github.repository }}
+          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number || '' }}  # If PR exists
+          REPORT_SUFFIX: pr
+
+      - name: Delete web app for PR Branch
+        if: always()
+        run: |
+          docker rm -f my-web-app-pr || true
+          docker rmi my-web-app-pr:latest || true
+          echo "PR branch web app deleted"
 
 
       # - name: compare the security report of main and pr
